databases:
  - name: backend
    databaseName: backend
    user: backend

services:
  - type: web
    name: backend
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: backend
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false